config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  get "up", to: "rails/health#show", as: :rails_health_check

  # root to: "posts#index"

  namespace :api do
    resources :posts, only: [:index, :show] do
      resources :comments, only: [:index]
    end
  end
  root 'home#index'
  get '*path', to: 'home#index', constraints: ->(request) do
    !request.xhr? && request.format.html?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Presentable


  belongs_to :post
  has_many :replies, class_name: 'Comment', foreign_key: 'parent_id', dependent: :destroy
  belongs_to :parent, class_name: 'Comment', foreign_key: 'parent_id', optional: true
  scope :by_score, -> { order(score: :desc) }
  scope :top_level, -> { where(parent_id: nil) }


  def top_level?
    parent_id.nil?
  end

  def to_json
    {a:1}
  end
  def as_json
    {a:1}
  end
end

app/models/post.rb
class Post < ApplicationRecord
  include Presentable

  has_many :comments, dependent: :destroy
end

app/models/presentable.rb
# Provides the presenter / decorate pattern
#
# Usage:
#   decorated_system = System.first.decorate
#
# If we ever want multiple presenter flavors it can just be called explicitly (instead of .decorate)
#
#   uniquely_decorated_system = UniqueSystemPresenter.new(System.first)
module Presentable
  def decorate
    "#{self.class}Presenter".constantize.new(self)
  end

  # add a class method named "decorate" that takes an array of objects and decorates each one
  # e.g. System.decorate(systems)
  def self.included(base)
    base.extend(ClassMethods)
  end

  # Add class level method
  module ClassMethods
    def decorate(collection)
      collection.map(&:decorate)
    end
  end
end

app/controllers/api/comments_controller.rb
# frozen_string_literal: true

module Api
  class CommentsController < ApplicationController
    def index
      @post = Post.find(params[:post_id])
      json = NestedCommentsService.new.perform(post: @post, levels: 3)
      render json: json
    end
  end
end

app/controllers/api/posts_controller.rb
module Api
  class PostsController < ApplicationController
    def index
      @posts = Post.decorate(Post.all)
    end

    def show
      post = Post.find(params[:id]).decorate
      @post = PostPresenter.new(post)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render file: Rails.root.join('app', 'assets', 'builds', 'index.html')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # GET /posts or /posts.json
  def index
    @posts = Post.decorate(Post.all)
  end

  # GET /posts/1 or /posts/1.json
  def show
    post = Post.find(params[:id]).decorate
    @post = PostPresenter.new(post)
    puts @post.as_json
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id]).decorate
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:author, :body, :title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/comments/_comment.html.erb
<div>
  by <strong><%= comment.author %></strong><br/>
  <%= comment.body %>
</div>
<br/>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<%= yield %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="speak divide-y divide-gray-100 rounded-lg bg-slate-100 p-3 mb-7">
  <p class="text-2xl mb-7 title"><%= post.title %> by r/<%=post.author %></p>
  <p class="body"><%= post.body_as_html %></p>
</div>

<div id="comments">
  <strong><%=post.comments.count %> comments</strong><br/><br/>
  <%= render partial: 'comments/comment', collection: post.comments, as: :comment %>
</div>

app/views/posts/_row.erb
<li class="flex justify-between gap-x-6 py-5 " id="<%= dom_id post %>">
  <div class="flex min-w-0 gap-x-4">
    <!--img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt=""-->
    <div class="min-w-0 flex-auto">
      <%= link_to post, class: 'text-gray-900 text-xl' do %>
        <%= post.title %>
      <% end %>
    </div>
  </div>
  <div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
    🔗
<!--    <p class="text-sm leading-6 text-gray-900">Co-Founder / CEO</p>-->
<!--    <p class="mt-1 text-xs leading-5 text-gray-500">Last seen <time datetime="2023-01-23T13:23Z">3h ago</time></p>-->
  </div>
</li>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div id="posts" data-posts="<%= @posts.to_json %>"></div>
<div id="root"></div>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<div id="root"></div>